config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, :rounds
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/round.rb
class Round < ApplicationRecord
  validates :place, :start, :end, presence: true

  has_many :users_and_rounds, inverse_of: :round
  has_many :users, through: :users_and_rounds

  accepts_nested_attributes_for :users
  accepts_nested_attributes_for :users_and_rounds, :allow_destroy => true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2 }, uniqueness: true

  has_many :users_and_rounds, inverse_of: :user
  has_many :rounds, through: :users_and_rounds

  accepts_nested_attributes_for :rounds
  accepts_nested_attributes_for :users_and_rounds, :allow_destroy => true
end

app/models/users_and_round.rb
class UsersAndRound < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  belongs_to :round, foreign_key: :round_id

  accepts_nested_attributes_for :user, :reject_if => :all_blank
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def index
    @rounds = Round.all
  end

  def new
    @round = Round.new
  end

  def edit
    @round = Round.find(params[:id])
  end

  def create
    @round = Round.new(round_params)
    if @round.save
      redirect_to rounds_path
    else
      render :new
    end
  end

  def update
    @round = Round.find(params[:id])
    if @round.update(round_params)
      redirect_to rounds_path
    else
      render :edit
    end
  end

  def destroy
    @round = Round.find(params[:id])
    @round.destroy
    redirect_to rounds_path
  end

  private

  def round_params
    params.require(:round).permit(:start, :end, :place,
      users_and_rounds_attributes: [:id, :user_id, :score_after30,
                                   :score_before30, :_destroy,
        user_attributes: [:id, :_destroy, :name]])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/_errors.html.erb
<% if resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(resource.errors.count, "error") %> prohibited
        this resource from being saved:
      </h2>
      <ul>
        <% resource.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Velobas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <%= link_to 'Велобаскетбол', rounds_path, :class => "nav-link navbar-brand active font-weight-bold" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Игроки', users_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Добавить игрока', new_user_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Добавить матч', new_round_path, :class => "nav-link" %>
      </li>
    </ul>
      <%= yield %>
  </body>
</html>

app/views/rounds/_form.html.erb
<%= simple_form_for @round do |f| %>

<%= render 'common/errors', resource: @round %>

<div class="col-md-6">
  <%= f.input :place, label: 'Стадион' %>
  <%= f.input :start, label: 'Начало матча' %>
  <%= f.input :end, label: 'Окончание' %>
  <%= f.association :users, as: :check_boxes %>


  <%= f.button :submit %>
  <%= link_to 'Вернуться', rounds_path %>
<% end %>
</div>

app/views/rounds/edit.html.erb
<h1>Редактировать пользователя</h1>

<%= render 'form' %>

app/views/rounds/index.html.erb
<h1>Все игроки</h1>

<table class="table table-striped table-bordered">
  <tr class="thead-inverse">
    <th>#</th>
    <th>Кто</th>
    <th>Очков</th>
    <th>Мячей после 30</th>
    <th>Мячей до 30</th>
    <th>Времени сыграно</th>
    <th>Ачивки</th>
    <th>Изменить</th>
    <th>Удалить</th>
  </tr>

  <% @rounds.each do |round| %>
    <tr>
      <td><%= round.id %></td>
      <td><%= round.place %></td>
      <td><%= round.start %></td>
      <td><%= round.end %></td>
      <td><%= round.users.count %></td>
      <td><%#= round.play_time %></td>
      <td><%#= round.achievement %></td>
      <td><%= link_to 'Изменить', edit_round_path(round) %></td>
      <td><%= link_to 'Удалить', round_path(round),
              method: :delete, data: { confirm: 'Вы уверены?' } %></td>
    </tr>
  <% end %>
</table>

app/views/rounds/new.html.erb
<h1>Создать пользователя</h1>

<%= render 'form' %>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>

  <%= render 'common/errors', resource: @user %>

<div class="col-md-6">
  <%= f.input :name, label: 'Имя или погремуха' %>
  <%= f.button :submit %>
  <%= link_to 'Вернуться', users_path %>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Редактировать матч</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Все игроки</h1>

<table class="table table-striped table-bordered">
  <tr class="thead-inverse">
    <th>#</th>
    <th>Кто</th>
    <th>Очков</th>
    <th>Мячей после 30</th>
    <th>Мячей до 30</th>
    <th>Времени сыграно</th>
    <th>Ачивки</th>
    <th>Изменить</th>
    <th>Удалить</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.total_score %></td>
      <td><%= user.dist_goal %></td>
      <td><%= user.close_goal %></td>
      <td><%= user.play_time %></td>
      <td><%= user.achievement %></td>
      <td><%= link_to 'Изменить', edit_user_path(user) %></td>
      <td><%= link_to 'Удалить', user_path(user),
              method: :delete, data: { confirm: 'Вы уверены?' } %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>Создать матч</h1>

<%= render 'form' %>

app/views/welcome/index.html.erb
<h1>Привет</h1>